name: Generator Windows

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform'
        required: false
        default: 'windows'
      version:
        description: 'RustDesk version'
        required: false
      appname:
        description: 'App Name'
        required: false
      server:
        description: 'Server address'
        required: false
      key:
        description: 'Public Key'
        required: false
      apiServer:
        description: 'API Server'
        required: false
      custom:
        description: 'Custom options'
        required: false
      uuid:
        description: 'UUID'
        required: false
      iconlink:
        description: 'Icon Link'
        required: false
      logolink:
        description: 'Logo Link'
        required: false
      extras:
        description: 'Extras'
        required: false
      filename:
        description: 'Filename'
        required: false

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug inputs
        run: |
          echo "Platform: ${{ inputs.platform }}"
          echo "Version: ${{ inputs.version }}"
          echo "App Name: ${{ inputs.appname }}"
          echo "Server: ${{ inputs.server }}"
          echo "Key: ${{ inputs.key }}"
          echo "Workflow запущен успешно!"
