on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform (windows, macos, etc.)'
        required: false
      version:
        description: 'RustDesk version'
        required: false
      app_name:
        description: 'App name'
        required: false
